# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: trailing-whitespace
      - id: check-toml
      - id: end-of-file-fixer

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v3.0.1
    hooks:
      - id: add-trailing-comma

  - repo: local
    hooks:
      - id: autoflake
        name: autoflake
        entry: bash -c 'cd api && poetry run autoflake --in-place --remove-all-unused-imports --remove-duplicate-keys -r .'
        language: system
        types: [python]

      - id: black
        name: Format with Black
        entry: bash -c 'cd api && poetry run black .'
        language: system
        types: [python]

      - id: isort
        name: isort
        entry: bash -c 'cd api && poetry run isort .'
        language: system
        types: [python]

      - id: flake8
        name: Check with Flake8
        entry: bash -c 'cd api && poetry run flake8 --count .'
        language: system
        pass_filenames: false
        types: [python]

      - id: mypy
        name: Validate types with MyPy
        entry: bash -c 'cd api && poetry run mypy .'
        language: system
        types: [python]
        pass_filenames: false
