services:
  web:
    image: next-app
    container_name: next-app
    build:
      context: ./web/
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app
      - ./web/node_modules:/app/node_modules
    restart: always
    tty: true
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
