name: Testing api

on: push

defaults:
  run:
    working-directory: api

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: |
          pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.11"
          cache: "poetry"
      - name: Install dependencies
        run: poetry install --with dev --no-interaction
      - name: Run black check
        run: poetry run black --check .
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: |
          pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.11"
          cache: "poetry"
      - name: Install dependencies
        run: poetry install --with dev --no-interaction
      - name: Run flake8 check
        run: poetry run flake8 --count .
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: |
          pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.11"
          cache: "poetry"
      - name: Install dependencies
        run: poetry install --with dev --no-interaction
      - name: Run mypy check
        run: poetry run mypy .
  pytest:
    runs-on: ubuntu-latest
    services:
      api-db:
        image: postgres:13.8-bullseye
        env:
          POSTGRES_PASSWORD: api
          POSTGRES_USER: api
          POSTGRES_DB: api
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: |
          pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.11"
          cache: "poetry"
      - name: Install dependencies
        run: poetry install --with dev --no-interaction
      - name: Run pytest check
        run: poetry run pytest -vv --cov="api" .
        env:
          API_HOST: "0.0.0.0"
          API_DB_HOST: localhost
