name: Testing api

on: push

defaults:
  run:
    working-directory: api

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.11"
        id: setup_python
      - name: Cache Packages
        uses: actions/cache@v3
        with:
          path: ~/.local
          key: poetry-local-${{ runner.os }}-${{ steps.setup_python.outputs.python-version }}-${{ hashFiles('**/api/poetry.lock') }}-${{ hashFiles('.github/workflows/*.yml') }}
      - name: Install deps
        run: |
          pip install -U pip
          pip install poetry
          poetry install
      - name: Run black check
        run: poetry run black --check .
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.11"
        id: setup_python
      - name: Cache Packages
        uses: actions/cache@v3
        with:
          path: ~/.local
          key: poetry-local-${{ runner.os }}-${{ steps.setup_python.outputs.python-version }}-${{ hashFiles('**/api/poetry.lock') }}-${{ hashFiles('.github/workflows/*.yml') }}
      - name: Install deps
        run: |
          pip install -U pip
          pip install poetry
          poetry install
      - name: Run flake8 check
        run: poetry run flake8 --count .
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.11"
        id: setup_python
      - name: Cache Packages
        uses: actions/cache@v3
        with:
          path: ~/.local
          key: poetry-local-${{ runner.os }}-${{ steps.setup_python.outputs.python-version }}-${{ hashFiles('**/api/poetry.lock') }}-${{ hashFiles('.github/workflows/*.yml') }}
      - name: Install deps
        run: |
          pip install -U pip
          pip install poetry
          poetry install
      - name: Run mypy check
        run: poetry run mypy .
  pytest:
    runs-on: ubuntu-latest
    services:
      api-db:
        image: postgres:13.8-bullseye
        env:
          POSTGRES_PASSWORD: api
          POSTGRES_USER: api
          POSTGRES_DB: api
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.11"
        id: setup_python
      - name: Cache Packages
        uses: actions/cache@v3
        with:
          path: ~/.local
          key: poetry-local-${{ runner.os }}-${{ steps.setup_python.outputs.python-version }}-${{ hashFiles('**/api/poetry.lock') }}-${{ hashFiles('.github/workflows/*.yml') }}
      - name: Install deps
        run: |
          pip install -U pip
          pip install poetry
          poetry install
      - name: Run pytest check
        run: poetry run pytest -vv --cov="api" .
        env:
          API_HOST: "0.0.0.0"
          API_DB_HOST: localhost
